blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/create/', views.BlogCreateView.as_view(), name='blog_create'),
    path('blog/list/', views.BlogListView.as_view(), name='blog_list'),
    path('blog/detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', views.BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', views.BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users_app.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=30, verbose_name="Заголовок", null=True)
    content = models.TextField()
    prev_image = models.ImageField(upload_to='images/', verbose_name="Изображение", null=True)
    created_at = models.DateField(verbose_name="Дата создания", auto_now_add=True)
    publication_flag = models.BooleanField(verbose_name="Признак публикации", null=True, default=False)
    number_of_views = models.IntegerField(verbose_name="Количество просмотров", null=False, default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'
        ordering = ['title']
        db_table = 'blog_records'

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

import blog
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'publication_flag']
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:blog_list')


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.filter(publication_flag=True)


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.number_of_views += 1
        obj.save()
        return obj


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'publication_flag']
    template_name = 'blog/blog_form.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('blog:blog_detail', args=(self.object.pk,))


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Блог </title>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mb-4"> Удалить ? </h1>
        <p> Вы уверены, что хотите удалить "{{ blog.title }}" ?</p>
        <form method="post">
            {% csrf_token%}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger"> Удалить </button>
            <a href="{% url 'blog:blog_list' %}"> Отменить </a>
        </form>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Блог </title>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mb-4"> {{ blog.title }} </h1>
        <p> Содержание: {{ blog.content }}</p>
        <p> Количество просмотров: {{ blog.number_of_views }}</p>
        <p> Создано: {{ blog.created_at }}</p>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Блог </title>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mb-4"> Форма блог </h1>
        <form method="post">
            {% csrf_token%}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary"> Сохранить </button>
            <a href="{% url 'blog:blog_list' %}"> Отменить </a>
        </form>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <h1 class="mb-4"> Список </h1>
        <a href="{% url 'blog:blog_create' %}" class="btn btn-primary"> Создать </a>
        <ul class="List-group">
            {% for blog in blogs %}
            <li class="List-group-item">
                <a href="{% url 'blog:blog_detail' blog.pk %}"> {{ blog.title }}</a>
                <a href="{% url 'blog:blog_update' blog.pk %}" class="btn btn-secondary"> Редактировать </a>
                <a href="{% url 'blog:blog_delete' blog.pk %}" class="btn btn-danger"> Удалить </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>